using System;
using System.Collections.Generic;
using System.Linq;
using Godot;

public enum QuestDifficulty
{
    Novice, Intermediate, Experienced, Master, Grandmaster, Mini, Special
}

public class QuestUnlock : Unlockable
{
    public String name { get; set; }
    public QuestDifficulty questDifficulty { get; set; }

    public QuestUnlock(String name)
    {
        this.name = name;
        unlockableType = UnlockableType.Quest;
    }

    public override bool RequirementsMet(List<SkillUnlock> unlocks, List<QuestUnlock> quests, int combatLevel = 0)
    {
        return true;
    }

#nullable enable
    public override Texture2D? GetTexture()
    {
        try
        {
            Texture2D texture = (Texture2D)GD.Load($"res://Resources/resource-packs/quests_tab/blue_quests_icon.png");
            return texture;
        }
        catch
        {
            return null;
        }
    }

    public override string ToString()
    {
        return $"{name}\n{questDifficulty}";
    }

    public override String DifficultyToString()
    {
        return $"{questDifficulty}";
    }

    public static List<QuestUnlock> GetRandomizedQuests(Random rand)
    {
        var allQuests = GetQuests();
        var difficulties = new[] {
            QuestDifficulty.Novice, QuestDifficulty.Intermediate, QuestDifficulty.Experienced,
            QuestDifficulty.Master, QuestDifficulty.Grandmaster, QuestDifficulty.Mini, QuestDifficulty.Special
        };

        List<QuestUnlock> result = new();
        foreach (var difficulty in difficulties)
        {
            var bracket = allQuests.Where(q => q.questDifficulty == difficulty).ToList();
            for (int i = bracket.Count - 1; i > 0; --i)
            {
                int j = rand.Next(i + 1);
                (bracket[i], bracket[j]) = (bracket[j], bracket[i]);
            }
            result.AddRange(bracket);
        }
        return result;
    }

    // This data was mostly generated by AI and it was a nightmare
    // It probably still has errors and should be double checked
    public static List<QuestUnlock> GetQuests()
    {
        List<QuestUnlock> quests = new();

        QuestUnlock Q(string name, QuestDifficulty difficulty,
                      (Skill, int)[]? skillReqs = null,
                      QuestUnlock[]? questReqs = null)
        {
            var q = new QuestUnlock(name) { questDifficulty = difficulty };
            if (skillReqs != null) q.skillRequirements.AddRange(skillReqs);
            if (questReqs != null) q.questRequirements.AddRange(questReqs);
            quests.Add(q);
            return q;
        }

        // ── Novice ──────────────────────────────────────────────────────────
        Q("Current Affairs",         QuestDifficulty.Novice, skillReqs: [(Skill.Sailing, 22)]);
        var druidicRitual = Q("Druidic Ritual",          QuestDifficulty.Novice);
        Q("The Ides of Milk",         QuestDifficulty.Novice);
        Q("A Porcine of Interest",    QuestDifficulty.Novice);
        Q("Alfred Grimhand's Barcrawl", QuestDifficulty.Novice);
        Q("Below Ice Mountain",       QuestDifficulty.Novice);
        var plagueCity = Q("Plague City",            QuestDifficulty.Novice);
        Q("Biohazard",                QuestDifficulty.Novice, questReqs: [plagueCity]);
        Q("Children of the Sun",      QuestDifficulty.Novice);
        Q("Client of Kourend",        QuestDifficulty.Novice);
        Q("Clock Tower",              QuestDifficulty.Novice);
        Q("Cook's Assistant",         QuestDifficulty.Novice);
        Q("Daddy's Home",             QuestDifficulty.Novice);
        Q("Death Plateau",            QuestDifficulty.Novice);
        Q("Demon Slayer",             QuestDifficulty.Novice);
        Q("Doric's Quest",            QuestDifficulty.Novice);
        Q("Dwarf Cannon",             QuestDifficulty.Novice);
        Q("Eagles' Peak",             QuestDifficulty.Novice, skillReqs: [(Skill.Hunter, 27)]);
        Q("Elemental Workshop I",     QuestDifficulty.Novice, skillReqs: [(Skill.Mining, 20)]);
        Q("Ernest the Chicken",       QuestDifficulty.Novice);
        Q("Ethically Acquired Antiquities", QuestDifficulty.Novice, skillReqs: [(Skill.Thieving, 25)]);
        Q("Fishing Contest",          QuestDifficulty.Novice, skillReqs: [(Skill.Fishing, 10)]);
        Q("Gertrude's Cat",           QuestDifficulty.Novice);
        Q("Goblin Diplomacy",         QuestDifficulty.Novice);
        Q("Hazeel Cult",              QuestDifficulty.Novice);
        Q("Imp Catcher",              QuestDifficulty.Novice);
        Q("Jungle Potion",            QuestDifficulty.Novice, questReqs: [druidicRitual]);
        Q("Learning the Ropes",       QuestDifficulty.Novice);
        Q("Misthalin Mystery",        QuestDifficulty.Novice);
        Q("Monk's Friend",            QuestDifficulty.Novice);
        Q("Murder Mystery",           QuestDifficulty.Novice);
        Q("Pandemonium",              QuestDifficulty.Novice);
        Q("Pirate's Treasure",        QuestDifficulty.Novice);
        Q("Priest in Peril",          QuestDifficulty.Novice);
        Q("Prince Ali Rescue",        QuestDifficulty.Novice);
        Q("Rag and Bone Man I",       QuestDifficulty.Novice);
        Q("Recruitment Drive",        QuestDifficulty.Novice);
        Q("Romeo & Juliet",           QuestDifficulty.Novice);
        Q("Rune Mysteries",           QuestDifficulty.Novice);
        Q("Sheep Herder",             QuestDifficulty.Novice);
        Q("Sheep Shearer",            QuestDifficulty.Novice);
        Q("Shield of Arrav",          QuestDifficulty.Novice);
        Q("Skippy and the Mogres",    QuestDifficulty.Novice, skillReqs: [(Skill.Cooking, 20)]);
        Q("The Restless Ghost",       QuestDifficulty.Novice);
        Q("The Ribbiting Tale of a Lily Pad Labour Dispute", QuestDifficulty.Novice, skillReqs: [(Skill.Woodcutting, 15)]);
        Q("Tower of Life",            QuestDifficulty.Novice, skillReqs: [(Skill.Construction, 10)]);
        Q("Vale Totems (miniquest)",  QuestDifficulty.Novice);
        Q("Witch's Potion",           QuestDifficulty.Novice);
        Q("X Marks the Spot",         QuestDifficulty.Novice);

        // ── Intermediate ─────────────────────────────────────────────────────
        Q("Quests/Intermediate",      QuestDifficulty.Intermediate);
        Q("Animal Magnetism",         QuestDifficulty.Intermediate);
        Q("Another Slice of H.A.M.", QuestDifficulty.Intermediate);
        Q("The Ascent of Arceuus",    QuestDifficulty.Intermediate);
        Q("At First Light",           QuestDifficulty.Intermediate, skillReqs: [(Skill.Hunter, 46)]);
        Q("Bear Your Soul",           QuestDifficulty.Intermediate);
        Q("Big Chompy Bird Hunting",  QuestDifficulty.Intermediate, skillReqs: [(Skill.Fletching, 5)]);
        Q("Black Knights' Fortress",  QuestDifficulty.Intermediate);
        Q("Bone Voyage",              QuestDifficulty.Intermediate);
        Q("Cold War",                 QuestDifficulty.Intermediate, skillReqs: [(Skill.Hunter, 10)]);
        Q("The Corsair Curse",        QuestDifficulty.Intermediate);
        Q("Creature of Fenkenstrain", QuestDifficulty.Intermediate);
        Q("Death on the Isle",        QuestDifficulty.Intermediate, skillReqs: [(Skill.Thieving, 34)]);
        Q("Death to the Dorgeshuun",  QuestDifficulty.Intermediate);
        Q("The Depths of Despair",    QuestDifficulty.Intermediate);
        Q("The Dig Site",             QuestDifficulty.Intermediate, skillReqs: [(Skill.Agility, 10)]);
        Q("Eadgar's Ruse",            QuestDifficulty.Intermediate);
        Q("Elemental Workshop II",    QuestDifficulty.Intermediate);
        Q("Enlightened Journey",      QuestDifficulty.Intermediate);
        Q("Enter the Abyss",          QuestDifficulty.Intermediate);
        Q("Fairytale I - Growing Pains", QuestDifficulty.Intermediate);
        Q("Family Pest",              QuestDifficulty.Intermediate);
        Q("The Feud",                 QuestDifficulty.Intermediate, skillReqs: [(Skill.Thieving, 30)]);
        Q("Fight Arena",              QuestDifficulty.Intermediate);
        Q("Forgettable Tale...",      QuestDifficulty.Intermediate, skillReqs: [(Skill.Cooking, 22)]);
        Q("The Forsaken Tower",       QuestDifficulty.Intermediate);
        var theFremennikTrials = Q("The Fremennik Trials",   QuestDifficulty.Intermediate);
        Q("The Garden of Death",      QuestDifficulty.Intermediate, skillReqs: [(Skill.Farming, 20)]);
        Q("Garden of Tranquillity",   QuestDifficulty.Intermediate, skillReqs: [(Skill.Farming, 25)]);
        Q("Getting Ahead",            QuestDifficulty.Intermediate, skillReqs: [(Skill.Crafting, 30)]);
        Q("Ghosts Ahoy",              QuestDifficulty.Intermediate);
        Q("The Giant Dwarf",          QuestDifficulty.Intermediate, skillReqs: [(Skill.Crafting, 12)]);
        Q("The Golem",                QuestDifficulty.Intermediate, skillReqs: [(Skill.Crafting, 20)]);
        var theGrandTree = Q("The Grand Tree",          QuestDifficulty.Intermediate, skillReqs: [(Skill.Agility, 25)]);
        Q("The Hand in the Sand",     QuestDifficulty.Intermediate, skillReqs: [(Skill.Thieving, 17)]);
        Q("Holy Grail",               QuestDifficulty.Intermediate);
        Q("Horror from the Deep",     QuestDifficulty.Intermediate, skillReqs: [(Skill.Agility, 35)]);
        Q("Icthlarin's Little Helper", QuestDifficulty.Intermediate);
        Q("In Aid of the Myreque",    QuestDifficulty.Intermediate);
        Q("In Search of the Myreque", QuestDifficulty.Intermediate);
        Q("The Knight's Sword",       QuestDifficulty.Intermediate, skillReqs: [(Skill.Mining, 10)]);
        Q("Lost City",                QuestDifficulty.Intermediate, skillReqs: [(Skill.Crafting, 31)]);
        Q("The Lost Tribe",           QuestDifficulty.Intermediate);
        var makingHistory = Q("Making History",          QuestDifficulty.Intermediate);
        Q("Merlin's Crystal",         QuestDifficulty.Intermediate);
        Q("Mountain Daughter",        QuestDifficulty.Intermediate, skillReqs: [(Skill.Agility, 20)]);
        Q("Nature Spirit",            QuestDifficulty.Intermediate);
        Q("Observatory Quest",        QuestDifficulty.Intermediate);
        Q("Prying Times",             QuestDifficulty.Intermediate, skillReqs: [(Skill.Smithing, 30)]);
        Q("The Queen of Thieves",     QuestDifficulty.Intermediate);
        Q("Ratcatchers",              QuestDifficulty.Intermediate);
        Q("Scorpion Catcher",         QuestDifficulty.Intermediate, skillReqs: [(Skill.Prayer, 31)]);
        Q("Scrambled!",               QuestDifficulty.Intermediate, skillReqs: [(Skill.Construction, 38)]);
        Q("Sea Slug",                 QuestDifficulty.Intermediate, skillReqs: [(Skill.Firemaking, 30)]);
        Q("Shades of Mort'ton",       QuestDifficulty.Intermediate);
        Q("Shadow of the Storm",      QuestDifficulty.Intermediate, skillReqs: [(Skill.Crafting, 30)]);
        Q("Shilo Village",            QuestDifficulty.Intermediate);
        Q("Sleeping Giants",          QuestDifficulty.Intermediate, skillReqs: [(Skill.Smithing, 15)]);
        Q("The Slug Menace",          QuestDifficulty.Intermediate);
        Q("A Soul's Bane",            QuestDifficulty.Intermediate);
        Q("Spirits of the Elid",      QuestDifficulty.Intermediate);
        Q("Tai Bwo Wannai Trio",      QuestDifficulty.Intermediate, skillReqs: [(Skill.Agility, 15)]);
        Q("A Tail of Two Cats",       QuestDifficulty.Intermediate);
        Q("Tale of the Righteous",    QuestDifficulty.Intermediate);
        Q("Tears of Guthix",          QuestDifficulty.Intermediate);
        Q("Temple of Ikov",           QuestDifficulty.Intermediate, skillReqs: [(Skill.Thieving, 42)]);
        Q("Temple of the Eye",        QuestDifficulty.Intermediate);
        Q("The Tourist Trap",         QuestDifficulty.Intermediate, skillReqs: [(Skill.Fletching, 10)]);
        Q("Tree Gnome Village",       QuestDifficulty.Intermediate);
        Q("Tribal Totem",             QuestDifficulty.Intermediate, skillReqs: [(Skill.Thieving, 21)]);
        Q("Troll Romance",            QuestDifficulty.Intermediate, skillReqs: [(Skill.Agility, 28)]);
        Q("Troll Stronghold",         QuestDifficulty.Intermediate);
        Q("Twilight's Promise",       QuestDifficulty.Intermediate);
        Q("Vampyre Slayer",           QuestDifficulty.Intermediate);
        Q("Wanted!",                  QuestDifficulty.Intermediate);
        Q("Watchtower",               QuestDifficulty.Intermediate);
        Q("Waterfall Quest",          QuestDifficulty.Intermediate);
        Q("What Lies Below",          QuestDifficulty.Intermediate);
        Q("Witch's House",            QuestDifficulty.Intermediate);
        Q("Zogre Flesh Eaters",       QuestDifficulty.Intermediate);
        Q("Olaf's Quest",             QuestDifficulty.Intermediate, questReqs: [theFremennikTrials]);
        Q("The Eyes of Glouphrie",    QuestDifficulty.Intermediate, questReqs: [theGrandTree]);
        Q("The Enchanted Key",        QuestDifficulty.Intermediate, questReqs: [makingHistory]);

        // ── Experienced ──────────────────────────────────────────────────────
        Q("Between a Rock...",        QuestDifficulty.Experienced);
        var cabinFever = Q("Cabin Fever",            QuestDifficulty.Experienced);
        Q("Contact!",                 QuestDifficulty.Experienced);
        Q("Darkness of Hallowvale",   QuestDifficulty.Experienced);
        Q("Defender of Varrock",      QuestDifficulty.Experienced, skillReqs: [(Skill.Smithing, 55)]);
        Q("Devious Minds",            QuestDifficulty.Experienced, skillReqs: [(Skill.Smithing, 65)]);
        Q("Dragon Slayer I",          QuestDifficulty.Experienced);
        Q("Enakhra's Lament",         QuestDifficulty.Experienced, skillReqs: [(Skill.Crafting, 50)]);
        Q("Fairytale II - Cure a Queen", QuestDifficulty.Experienced);
        Q("Family Crest",             QuestDifficulty.Experienced, skillReqs: [(Skill.Mining, 40)]);
        Q("The Fremennik Isles",      QuestDifficulty.Experienced);
        Q("Haunted Mine",             QuestDifficulty.Experienced);
        Q("The Heart of Darkness",    QuestDifficulty.Experienced, skillReqs: [(Skill.Mining, 55)]);
        Q("Heroes' Quest",            QuestDifficulty.Experienced);
        Q("King's Ransom",            QuestDifficulty.Experienced);
        Q("A Kingdom Divided",        QuestDifficulty.Experienced);
        Q("Land of the Goblins",      QuestDifficulty.Experienced);
        Q("Lunar Diplomacy",          QuestDifficulty.Experienced);
        Q("Meat and Greet",           QuestDifficulty.Experienced);
        Q("My Arm's Big Adventure",   QuestDifficulty.Experienced, skillReqs: [(Skill.Farming, 29)]);
        Q("One Small Favour",         QuestDifficulty.Experienced);
        Q("The Path of Glouphrie",    QuestDifficulty.Experienced);
        Q("Rag and Bone Man II",      QuestDifficulty.Experienced, skillReqs: [(Skill.Slayer, 40)]);
        Q("Roving Elves",             QuestDifficulty.Experienced);
        Q("Royal Trouble",            QuestDifficulty.Experienced, skillReqs: [(Skill.Agility, 40)]);
        Q("Rum Deal",                 QuestDifficulty.Experienced);
        Q("Shadows of Custodia",      QuestDifficulty.Experienced);
        Q("A Taste of Hope",          QuestDifficulty.Experienced);
        Q("The Red Reef",             QuestDifficulty.Experienced, skillReqs: [(Skill.Sailing, 52)]);
        Q("Throne of Miscellania",    QuestDifficulty.Experienced);
        Q("Troubled Tortugans",       QuestDifficulty.Experienced, skillReqs: [(Skill.Slayer, 51)]);
        Q("The Great Brain Robbery",  QuestDifficulty.Experienced, skillReqs: [(Skill.Crafting, 16)], questReqs: [cabinFever]);

        // ── Master ───────────────────────────────────────────────────────────
        Q("Beneath Cursed Sands",     QuestDifficulty.Master);
        Q("Desert Treasure I",        QuestDifficulty.Master);
        Q("Dream Mentor",             QuestDifficulty.Master);
        Q("The Fremennik Exiles",     QuestDifficulty.Master, skillReqs: [(Skill.Crafting, 65)]);
        Q("Grim Tales",               QuestDifficulty.Master);
        Q("Legends' Quest",           QuestDifficulty.Master);
        Q("Making Friends with My Arm", QuestDifficulty.Master, skillReqs: [(Skill.Firemaking, 66)]);
        Q("Monkey Madness I",         QuestDifficulty.Master);
        Q("Mourning's End Part I",    QuestDifficulty.Master);
        Q("Mourning's End Part II",   QuestDifficulty.Master);
        Q("A Night at the Theatre",   QuestDifficulty.Master);
        Q("Perilous Moons",           QuestDifficulty.Master, skillReqs: [(Skill.Slayer, 48)]);
        Q("Secrets of the North",     QuestDifficulty.Master, skillReqs: [(Skill.Agility, 69)]);
        Q("Sins of the Father",       QuestDifficulty.Master);
        Q("Swan Song",                QuestDifficulty.Master);
        Q("The Curse of Arrav",       QuestDifficulty.Master, skillReqs: [(Skill.Mining, 64)]);
        Q("The Final Dawn",           QuestDifficulty.Master, skillReqs: [(Skill.Thieving, 66)]);

        // ── Grandmaster (circular refs — create all four first, then wire) ───
        var dragonSlayerIi = Q("Dragon Slayer II",       QuestDifficulty.Grandmaster,
            skillReqs: [(Skill.Agility, 60), (Skill.Thieving, 60), (Skill.Construction, 50),
                        (Skill.Smithing, 70), (Skill.Mining, 68), (Skill.Crafting, 62)]);
        var whileGuthixSleeps = Q("While Guthix Sleeps",    QuestDifficulty.Grandmaster,
            skillReqs: [(Skill.Agility, 66), (Skill.Farming, 65), (Skill.Herblore, 65),
                        (Skill.Hunter, 62), (Skill.Thieving, 72)]);
        var songOfTheElves = Q("Song of the Elves",      QuestDifficulty.Grandmaster,
            skillReqs: [(Skill.Agility, 70), (Skill.Construction, 70), (Skill.Farming, 70),
                        (Skill.Herblore, 70), (Skill.Hunter, 70), (Skill.Mining, 70),
                        (Skill.Smithing, 70), (Skill.Woodcutting, 70), (Skill.Prayer, 40)]);
        var monkeyMadnessIi = Q("Monkey Madness II",     QuestDifficulty.Grandmaster,
            skillReqs: [(Skill.Agility, 55), (Skill.Thieving, 55), (Skill.Slayer, 69),
                        (Skill.Hunter, 60), (Skill.Crafting, 70), (Skill.Firemaking, 60)]);

        dragonSlayerIi.questRequirements.AddRange([whileGuthixSleeps, songOfTheElves]);
        whileGuthixSleeps.questRequirements.Add(dragonSlayerIi);
        songOfTheElves.questRequirements.Add(dragonSlayerIi);

        Q("Desert Treasure II - The Fallen Empire", QuestDifficulty.Grandmaster,
            skillReqs: [(Skill.Firemaking, 75), (Skill.Mining, 60), (Skill.Construction, 60),
                        (Skill.Herblore, 62), (Skill.Runecraft, 60), (Skill.Thieving, 70)],
            questReqs: [dragonSlayerIi, monkeyMadnessIi]);
        Q("The Blood Moon Rises",     QuestDifficulty.Grandmaster, questReqs: [songOfTheElves]);

        // ── Special ──────────────────────────────────────────────────────────
        Q("Recipe for Disaster",      QuestDifficulty.Special);
        Q("Recipe for Disaster/Another Cook's Quest",       QuestDifficulty.Special, skillReqs: [(Skill.Cooking, 10)]);
        Q("Recipe for Disaster/Defeating the Culinaromancer", QuestDifficulty.Special);
        Q("Recipe for Disaster/Freeing Evil Dave",          QuestDifficulty.Special);
        Q("Recipe for Disaster/Freeing King Awowogei",      QuestDifficulty.Special, skillReqs: [(Skill.Cooking, 70)]);
        Q("Recipe for Disaster/Freeing Pirate Pete",        QuestDifficulty.Special, skillReqs: [(Skill.Cooking, 31)]);
        Q("Recipe for Disaster/Freeing Sir Amik Varze",     QuestDifficulty.Special);
        Q("Recipe for Disaster/Freeing Skrach Uglogwee",    QuestDifficulty.Special, skillReqs: [(Skill.Cooking, 41)]);
        Q("Recipe for Disaster/Freeing the Goblin generals", QuestDifficulty.Special);
        Q("Recipe for Disaster/Freeing the Lumbridge Guide", QuestDifficulty.Special, skillReqs: [(Skill.Cooking, 40)]);
        Q("Recipe for Disaster/Freeing the Mountain Dwarf", QuestDifficulty.Special);

        return quests;
    }
}