using System;
using System.Collections.Generic;
using Godot;

public enum QuestDifficulty
{
    Novice, Intermediate, Experienced, Master, Grandmaster, Mini, Special
}

public class QuestUnlock : Unlockable
{
    public String name;
    public QuestDifficulty questDifficulty;
    #nullable enable
    public Monster? toughestEnemy;

    public QuestUnlock(String name)
    {
        this.name = name;
    }

    public override bool RequirementsMet(List<SkillUnlock> unlocks, List<QuestUnlock> quests, int combatLevel = 0)
    {
        return true;
    }

    public override Texture2D? GetTexture()
    {
        try
        {
            ImageTexture texture = new ImageTexture();
            Image image = new Image();
            image.Load($"Resources/resource-packs/quests_tab/blue_quests_icon.png");
            texture.SetImage(image);
            return texture;
        }
        catch
        {
            return null;
        }
    }

    public override string ToString()
    {
        return $"{name}\n{questDifficulty}";
    }

    // This data was mostly generated by AI and it was a nightmare
    // It probably still has errors and should be double checked
    public static List<QuestUnlock> GetQuests()
    {
        List<QuestUnlock> quests = new();

        QuestUnlock APorcineOfInterest = new("A Porcine of Interest");
        APorcineOfInterest.questDifficulty = QuestDifficulty.Novice;
        quests.Add(APorcineOfInterest);

        QuestUnlock AlfredGrimhandsBarcrawl = new("Alfred Grimhand's Barcrawl");
        AlfredGrimhandsBarcrawl.questDifficulty = QuestDifficulty.Novice;
        quests.Add(AlfredGrimhandsBarcrawl);

        QuestUnlock BelowIceMountain = new("Below Ice Mountain");
        BelowIceMountain.questDifficulty = QuestDifficulty.Novice;
        quests.Add(BelowIceMountain);

        QuestUnlock PlagueCity = new("Plague City");
        PlagueCity.questDifficulty = QuestDifficulty.Novice;
        quests.Add(PlagueCity);

        QuestUnlock Biohazard = new("Biohazard");
        Biohazard.questDifficulty = QuestDifficulty.Novice;
        // Biohazard requires Plague City
        Biohazard.questRequirements.Add(PlagueCity);
        quests.Add(Biohazard);

        QuestUnlock ChildrenOfTheSun = new("Children of the Sun");
        ChildrenOfTheSun.questDifficulty = QuestDifficulty.Novice;
        quests.Add(ChildrenOfTheSun);

        QuestUnlock ClientOfKourend = new("Client of Kourend");
        ClientOfKourend.questDifficulty = QuestDifficulty.Novice;
        quests.Add(ClientOfKourend);

        QuestUnlock ClockTower = new("Clock Tower");
        ClockTower.questDifficulty = QuestDifficulty.Novice;
        quests.Add(ClockTower);

        QuestUnlock CooksAssistant = new("Cook's Assistant");
        CooksAssistant.questDifficulty = QuestDifficulty.Novice;
        quests.Add(CooksAssistant);

        QuestUnlock CurrentAffairs = new("Current Affairs");
        CurrentAffairs.questDifficulty = QuestDifficulty.Novice;
        CurrentAffairs.skillRequirements.Add((Skill.Sailing, 22));
        quests.Add(CurrentAffairs);

        QuestUnlock DaddysHome = new("Daddy's Home");
        DaddysHome.questDifficulty = QuestDifficulty.Novice;
        quests.Add(DaddysHome);

        QuestUnlock DeathPlateau = new("Death Plateau");
        DeathPlateau.questDifficulty = QuestDifficulty.Novice;
        quests.Add(DeathPlateau);

        QuestUnlock DemonSlayer = new("Demon Slayer");
        DemonSlayer.questDifficulty = QuestDifficulty.Novice;
        quests.Add(DemonSlayer);

        QuestUnlock DoricsQuest = new("Doric's Quest");
        DoricsQuest.questDifficulty = QuestDifficulty.Novice;
        quests.Add(DoricsQuest);

        QuestUnlock DruidicRitual = new("Druidic Ritual");
        DruidicRitual.questDifficulty = QuestDifficulty.Novice;
        quests.Add(DruidicRitual);

        QuestUnlock DwarfCannon = new("Dwarf Cannon");
        DwarfCannon.questDifficulty = QuestDifficulty.Novice;
        quests.Add(DwarfCannon);

        QuestUnlock EaglesPeak = new("Eagles' Peak");
        EaglesPeak.questDifficulty = QuestDifficulty.Novice;
        EaglesPeak.skillRequirements.Add((Skill.Hunter, 27));
        quests.Add(EaglesPeak);

        QuestUnlock ElementalWorkshopI = new("Elemental Workshop I");
        ElementalWorkshopI.questDifficulty = QuestDifficulty.Novice;
        ElementalWorkshopI.skillRequirements.Add((Skill.Mining, 20));
        quests.Add(ElementalWorkshopI);

        QuestUnlock ErnestTheChicken = new("Ernest the Chicken");
        ErnestTheChicken.questDifficulty = QuestDifficulty.Novice;
        quests.Add(ErnestTheChicken);

        QuestUnlock EthicallyAcquiredAntiquities = new("Ethically Acquired Antiquities");
        EthicallyAcquiredAntiquities.questDifficulty = QuestDifficulty.Novice;
        EthicallyAcquiredAntiquities.skillRequirements.Add((Skill.Thieving, 25));
        quests.Add(EthicallyAcquiredAntiquities);

        QuestUnlock FishingContest = new("Fishing Contest");
        FishingContest.questDifficulty = QuestDifficulty.Novice;
        FishingContest.skillRequirements.Add((Skill.Fishing, 10));
        quests.Add(FishingContest);

        QuestUnlock GertrudesCat = new("Gertrude's Cat");
        GertrudesCat.questDifficulty = QuestDifficulty.Novice;
        quests.Add(GertrudesCat);

        QuestUnlock GoblinDiplomacy = new("Goblin Diplomacy");
        GoblinDiplomacy.questDifficulty = QuestDifficulty.Novice;
        quests.Add(GoblinDiplomacy);

        QuestUnlock HazeelCult = new("Hazeel Cult");
        HazeelCult.questDifficulty = QuestDifficulty.Novice;
        quests.Add(HazeelCult);

        QuestUnlock ImpCatcher = new("Imp Catcher");
        ImpCatcher.questDifficulty = QuestDifficulty.Novice;
        quests.Add(ImpCatcher);

        QuestUnlock JunglePotion = new("Jungle Potion");
        JunglePotion.questDifficulty = QuestDifficulty.Novice;
        // Jungle Potion requires Druidic Ritual
        JunglePotion.questRequirements.Add(DruidicRitual);
        quests.Add(JunglePotion);

        QuestUnlock LearningTheRopes = new("Learning the Ropes");
        LearningTheRopes.questDifficulty = QuestDifficulty.Novice;
        quests.Add(LearningTheRopes);

        QuestUnlock MisthalinMystery = new("Misthalin Mystery");
        MisthalinMystery.questDifficulty = QuestDifficulty.Novice;
        quests.Add(MisthalinMystery);

        QuestUnlock MonksFriend = new("Monk's Friend");
        MonksFriend.questDifficulty = QuestDifficulty.Novice;
        quests.Add(MonksFriend);

        QuestUnlock MurderMystery = new("Murder Mystery");
        MurderMystery.questDifficulty = QuestDifficulty.Novice;
        quests.Add(MurderMystery);

        QuestUnlock Pandemonium = new("Pandemonium");
        Pandemonium.questDifficulty = QuestDifficulty.Novice;
        quests.Add(Pandemonium);

        QuestUnlock PiratesTreasure = new("Pirate's Treasure");
        PiratesTreasure.questDifficulty = QuestDifficulty.Novice;
        quests.Add(PiratesTreasure);

        QuestUnlock PriestInPeril = new("Priest in Peril");
        PriestInPeril.questDifficulty = QuestDifficulty.Novice;
        quests.Add(PriestInPeril);

        QuestUnlock PrinceAliRescue = new("Prince Ali Rescue");
        PrinceAliRescue.questDifficulty = QuestDifficulty.Novice;
        quests.Add(PrinceAliRescue);

        QuestUnlock RagAndBoneManI = new("Rag and Bone Man I");
        RagAndBoneManI.questDifficulty = QuestDifficulty.Novice;
        quests.Add(RagAndBoneManI);

        QuestUnlock RecruitmentDrive = new("Recruitment Drive");
        RecruitmentDrive.questDifficulty = QuestDifficulty.Novice;
        quests.Add(RecruitmentDrive);

        QuestUnlock RomeoAndJuliet = new("Romeo & Juliet");
        RomeoAndJuliet.questDifficulty = QuestDifficulty.Novice;
        quests.Add(RomeoAndJuliet);

        QuestUnlock RuneMysteries = new("Rune Mysteries");
        RuneMysteries.questDifficulty = QuestDifficulty.Novice;
        quests.Add(RuneMysteries);

        QuestUnlock SheepHerder = new("Sheep Herder");
        SheepHerder.questDifficulty = QuestDifficulty.Novice;
        quests.Add(SheepHerder);

        QuestUnlock SheepShearer = new("Sheep Shearer");
        SheepShearer.questDifficulty = QuestDifficulty.Novice;
        quests.Add(SheepShearer);

        QuestUnlock ShieldOfArrav = new("Shield of Arrav");
        ShieldOfArrav.questDifficulty = QuestDifficulty.Novice;
        quests.Add(ShieldOfArrav);

        QuestUnlock SkippyAndTheMogres = new("Skippy and the Mogres");
        SkippyAndTheMogres.questDifficulty = QuestDifficulty.Novice;
        SkippyAndTheMogres.skillRequirements.Add((Skill.Cooking, 20));
        quests.Add(SkippyAndTheMogres);

        QuestUnlock TheRestlessGhost = new("The Restless Ghost");
        TheRestlessGhost.questDifficulty = QuestDifficulty.Novice;
        quests.Add(TheRestlessGhost);

        QuestUnlock TheRibbitingTaleOfALilyPadLabourDispute = new("The Ribbiting Tale of a Lily Pad Labour Dispute");
        TheRibbitingTaleOfALilyPadLabourDispute.questDifficulty = QuestDifficulty.Novice;
        TheRibbitingTaleOfALilyPadLabourDispute.skillRequirements.Add((Skill.Woodcutting, 15));
        quests.Add(TheRibbitingTaleOfALilyPadLabourDispute);

        QuestUnlock TowerOfLife = new("Tower of Life");
        TowerOfLife.questDifficulty = QuestDifficulty.Novice;
        TowerOfLife.skillRequirements.Add((Skill.Construction, 10));
        quests.Add(TowerOfLife);

        QuestUnlock ValeTotemsMiniquest = new("Vale Totems (miniquest)");
        ValeTotemsMiniquest.questDifficulty = QuestDifficulty.Novice;
        quests.Add(ValeTotemsMiniquest);

        QuestUnlock WitchsPotion = new("Witch's Potion");
        WitchsPotion.questDifficulty = QuestDifficulty.Novice;
        quests.Add(WitchsPotion);

        QuestUnlock XMarksTheSpot = new("X Marks the Spot");
        XMarksTheSpot.questDifficulty = QuestDifficulty.Novice;
        quests.Add(XMarksTheSpot);

        // Intermediate quests
        QuestUnlock QuestsIntermediate = new("Quests/Intermediate");
        QuestsIntermediate.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(QuestsIntermediate);
        QuestUnlock AnimalMagnetism = new("Animal Magnetism");
        AnimalMagnetism.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(AnimalMagnetism);
        QuestUnlock AnotherSliceOfHAM = new("Another Slice of H.A.M.");
        AnotherSliceOfHAM.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(AnotherSliceOfHAM);
        //AnotherSliceOfHAM.skillRequirements.Add((Skill.Attack, 15));
        QuestUnlock TheAscentOfArceuus = new("The Ascent of Arceuus");
        TheAscentOfArceuus.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheAscentOfArceuus);
        QuestUnlock AtFirstLight = new("At First Light");
        AtFirstLight.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(AtFirstLight);
        AtFirstLight.skillRequirements.Add((Skill.Hunter, 46));
        QuestUnlock BearYourSoul = new("Bear Your Soul");
        BearYourSoul.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(BearYourSoul);
        QuestUnlock BigChompyBirdHunting = new("Big Chompy Bird Hunting");
        BigChompyBirdHunting.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(BigChompyBirdHunting);
        BigChompyBirdHunting.skillRequirements.Add((Skill.Fletching, 5));
        QuestUnlock BlackKnightsFortress = new("Black Knights' Fortress");
        BlackKnightsFortress.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(BlackKnightsFortress);
        QuestUnlock BoneVoyage = new("Bone Voyage");
        BoneVoyage.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(BoneVoyage);
        QuestUnlock ColdWar = new("Cold War");
        ColdWar.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ColdWar);
        ColdWar.skillRequirements.Add((Skill.Hunter, 10));
        QuestUnlock TheCorsairCurse = new("The Corsair Curse");
        TheCorsairCurse.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheCorsairCurse);
        QuestUnlock CreatureOfFenkenstrain = new("Creature of Fenkenstrain");
        CreatureOfFenkenstrain.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(CreatureOfFenkenstrain);
        QuestUnlock DeathOnTheIsle = new("Death on the Isle");
        DeathOnTheIsle.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(DeathOnTheIsle);
        DeathOnTheIsle.skillRequirements.Add((Skill.Thieving, 34));
        QuestUnlock DeathToTheDorgeshuun = new("Death to the Dorgeshuun");
        DeathToTheDorgeshuun.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(DeathToTheDorgeshuun);
        QuestUnlock TheDepthsOfDespair = new("The Depths of Despair");
        TheDepthsOfDespair.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheDepthsOfDespair);
        QuestUnlock TheDigSite = new("The Dig Site");
        TheDigSite.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheDigSite);
        TheDigSite.skillRequirements.Add((Skill.Agility, 10));
        QuestUnlock EadgarSRuse = new("Eadgar's Ruse");
        EadgarSRuse.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(EadgarSRuse);
        QuestUnlock ElementalWorkshopIi = new("Elemental Workshop II");
        ElementalWorkshopIi.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ElementalWorkshopIi);
        //ElementalWorkshopIi.skillRequirements.Add((Skill.Magic, 20));
        QuestUnlock EnlightenedJourney = new("Enlightened Journey");
        EnlightenedJourney.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(EnlightenedJourney);
        QuestUnlock EnterTheAbyss = new("Enter the Abyss");
        EnterTheAbyss.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(EnterTheAbyss);
        QuestUnlock FairytaleIGrowingPains = new("Fairytale I - Growing Pains");
        FairytaleIGrowingPains.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(FairytaleIGrowingPains);
        QuestUnlock FamilyPest = new("Family Pest");
        FamilyPest.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(FamilyPest);
        QuestUnlock TheFeud = new("The Feud");
        TheFeud.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheFeud);
        TheFeud.skillRequirements.Add((Skill.Thieving, 30));
        QuestUnlock FightArena = new("Fight Arena");
        FightArena.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(FightArena);
        QuestUnlock ForgettableTale = new("Forgettable Tale...");
        ForgettableTale.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ForgettableTale);
        ForgettableTale.skillRequirements.Add((Skill.Cooking, 22));
        QuestUnlock TheForsakenTower = new("The Forsaken Tower");
        TheForsakenTower.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheForsakenTower);
        QuestUnlock TheFremennikTrials = new("The Fremennik Trials");
        TheFremennikTrials.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheFremennikTrials);
        QuestUnlock TheGardenOfDeath = new("The Garden of Death");
        TheGardenOfDeath.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheGardenOfDeath);
        TheGardenOfDeath.skillRequirements.Add((Skill.Farming, 20));
        QuestUnlock GardenOfTranquillity = new("Garden of Tranquillity");
        GardenOfTranquillity.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(GardenOfTranquillity);
        GardenOfTranquillity.skillRequirements.Add((Skill.Farming, 25));
        QuestUnlock GettingAhead = new("Getting Ahead");
        GettingAhead.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(GettingAhead);
        GettingAhead.skillRequirements.Add((Skill.Crafting, 30));
        QuestUnlock GhostsAhoy = new("Ghosts Ahoy");
        GhostsAhoy.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(GhostsAhoy);
        QuestUnlock TheGiantDwarf = new("The Giant Dwarf");
        TheGiantDwarf.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheGiantDwarf);
        TheGiantDwarf.skillRequirements.Add((Skill.Crafting, 12));
        QuestUnlock TheGolem = new("The Golem");
        TheGolem.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheGolem);
        TheGolem.skillRequirements.Add((Skill.Crafting, 20));
        QuestUnlock TheGrandTree = new("The Grand Tree");
        TheGrandTree.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheGrandTree);
        TheGrandTree.skillRequirements.Add((Skill.Agility, 25));
        QuestUnlock TheHandInTheSand = new("The Hand in the Sand");
        TheHandInTheSand.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheHandInTheSand);
        TheHandInTheSand.skillRequirements.Add((Skill.Thieving, 17));
        QuestUnlock HolyGrail = new("Holy Grail");
        HolyGrail.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(HolyGrail);
        QuestUnlock HorrorFromTheDeep = new("Horror from the Deep");
        HorrorFromTheDeep.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(HorrorFromTheDeep);
        HorrorFromTheDeep.skillRequirements.Add((Skill.Agility, 35));
        QuestUnlock IcthlarinSLittleHelper = new("Icthlarin's Little Helper");
        IcthlarinSLittleHelper.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(IcthlarinSLittleHelper);
        QuestUnlock InAidOfTheMyreque = new("In Aid of the Myreque");
        InAidOfTheMyreque.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(InAidOfTheMyreque);
        QuestUnlock InSearchOfTheMyreque = new("In Search of the Myreque");
        InSearchOfTheMyreque.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(InSearchOfTheMyreque);
        QuestUnlock TheKnightSSword = new("The Knight's Sword");
        TheKnightSSword.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheKnightSSword);
        TheKnightSSword.skillRequirements.Add((Skill.Mining, 10));
        QuestUnlock LostCity = new("Lost City");
        LostCity.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(LostCity);
        LostCity.skillRequirements.Add((Skill.Crafting, 31));
        QuestUnlock TheLostTribe = new("The Lost Tribe");
        TheLostTribe.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheLostTribe);
        QuestUnlock MakingHistory = new("Making History");
        MakingHistory.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(MakingHistory);
        QuestUnlock MerlinSCrystal = new("Merlin's Crystal");
        MerlinSCrystal.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(MerlinSCrystal);
        QuestUnlock MountainDaughter = new("Mountain Daughter");
        MountainDaughter.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(MountainDaughter);
        MountainDaughter.skillRequirements.Add((Skill.Agility, 20));
        QuestUnlock NatureSpirit = new("Nature Spirit");
        NatureSpirit.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(NatureSpirit);
        QuestUnlock ObservatoryQuest = new("Observatory Quest");
        ObservatoryQuest.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ObservatoryQuest);
        QuestUnlock PryingTimes = new("Prying Times");
        PryingTimes.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(PryingTimes);
        PryingTimes.skillRequirements.Add((Skill.Smithing, 30));
        QuestUnlock TheQueenOfThieves = new("The Queen of Thieves");
        TheQueenOfThieves.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheQueenOfThieves);
        QuestUnlock Ratcatchers = new("Ratcatchers");
        Ratcatchers.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(Ratcatchers);
        QuestUnlock ScorpionCatcher = new("Scorpion Catcher");
        ScorpionCatcher.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ScorpionCatcher);
        ScorpionCatcher.skillRequirements.Add((Skill.Prayer, 31));
        QuestUnlock Scrambled = new("Scrambled!");
        Scrambled.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(Scrambled);
        Scrambled.skillRequirements.Add((Skill.Construction, 38));
        QuestUnlock SeaSlug = new("Sea Slug");
        SeaSlug.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(SeaSlug);
        SeaSlug.skillRequirements.Add((Skill.Firemaking, 30));
        QuestUnlock ShadesOfMortTon = new("Shades of Mort'ton");
        ShadesOfMortTon.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ShadesOfMortTon);
        QuestUnlock ShadowOfTheStorm = new("Shadow of the Storm");
        ShadowOfTheStorm.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ShadowOfTheStorm);
        ShadowOfTheStorm.skillRequirements.Add((Skill.Crafting, 30));
        QuestUnlock ShiloVillage = new("Shilo Village");
        ShiloVillage.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ShiloVillage);
        QuestUnlock SleepingGiants = new("Sleeping Giants");
        SleepingGiants.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(SleepingGiants);
        SleepingGiants.skillRequirements.Add((Skill.Smithing, 15));
        QuestUnlock TheSlugMenace = new("The Slug Menace");
        TheSlugMenace.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheSlugMenace);
        QuestUnlock ASoulSBane = new("A Soul's Bane");
        ASoulSBane.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ASoulSBane);
        QuestUnlock SpiritsOfTheElid = new("Spirits of the Elid");
        SpiritsOfTheElid.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(SpiritsOfTheElid);
        //SpiritsOfTheElid.skillRequirements.Add((Skill.Magic, 33));
        QuestUnlock TaiBwoWannaiTrio = new("Tai Bwo Wannai Trio");
        TaiBwoWannaiTrio.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TaiBwoWannaiTrio);
        TaiBwoWannaiTrio.skillRequirements.Add((Skill.Agility, 15));
        QuestUnlock ATailOfTwoCats = new("A Tail of Two Cats");
        ATailOfTwoCats.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ATailOfTwoCats);
        QuestUnlock TaleOfTheRighteous = new("Tale of the Righteous");
        TaleOfTheRighteous.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TaleOfTheRighteous);
        QuestUnlock TearsOfGuthix = new("Tears of Guthix");
        TearsOfGuthix.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TearsOfGuthix);
        QuestUnlock TempleOfIkov = new("Temple of Ikov");
        TempleOfIkov.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TempleOfIkov);
        TempleOfIkov.skillRequirements.Add((Skill.Thieving, 42));
        QuestUnlock TempleOfTheEye = new("Temple of the Eye");
        TempleOfTheEye.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TempleOfTheEye);
        QuestUnlock TheTouristTrap = new("The Tourist Trap");
        TheTouristTrap.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheTouristTrap);
        TheTouristTrap.skillRequirements.Add((Skill.Fletching, 10));
        QuestUnlock TreeGnomeVillage = new("Tree Gnome Village");
        TreeGnomeVillage.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TreeGnomeVillage);
        QuestUnlock TribalTotem = new("Tribal Totem");
        TribalTotem.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TribalTotem);
        TribalTotem.skillRequirements.Add((Skill.Thieving, 21));
        QuestUnlock TrollRomance = new("Troll Romance");
        TrollRomance.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TrollRomance);
        TrollRomance.skillRequirements.Add((Skill.Agility, 28));
        QuestUnlock TrollStronghold = new("Troll Stronghold");
        TrollStronghold.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TrollStronghold);
        QuestUnlock TwilightSPromise = new("Twilight's Promise");
        TwilightSPromise.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TwilightSPromise);
        QuestUnlock VampyreSlayer = new("Vampyre Slayer");
        VampyreSlayer.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(VampyreSlayer);
        QuestUnlock Wanted = new("Wanted!");
        Wanted.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(Wanted);
        QuestUnlock Watchtower = new("Watchtower");
        Watchtower.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(Watchtower);
        //Watchtower.skillRequirements.Add((Skill.Magic, 14));
        QuestUnlock WaterfallQuest = new("Waterfall Quest");
        WaterfallQuest.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(WaterfallQuest);
        QuestUnlock WhatLiesBelow = new("What Lies Below");
        WhatLiesBelow.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(WhatLiesBelow);
        QuestUnlock WitchSHouse = new("Witch's House");
        WitchSHouse.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(WitchSHouse);
        QuestUnlock ZogreFleshEaters = new("Zogre Flesh Eaters");
        ZogreFleshEaters.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(ZogreFleshEaters);
        QuestUnlock OlafSQuest = new("Olaf's Quest");
        OlafSQuest.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(OlafSQuest);
        OlafSQuest.questRequirements.Add(TheFremennikTrials);
        QuestUnlock TheEyesOfGlouphrie = new("The Eyes of Glouphrie");
        TheEyesOfGlouphrie.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheEyesOfGlouphrie);
        TheEyesOfGlouphrie.questRequirements.Add(TheGrandTree);
        QuestUnlock TheEnchantedKey = new("The Enchanted Key");
        TheEnchantedKey.questDifficulty = QuestDifficulty.Intermediate;
        quests.Add(TheEnchantedKey);
        TheEnchantedKey.questRequirements.Add(MakingHistory);

        // Experienced quests
        QuestUnlock BetweenARock = new("Between a Rock...");
        BetweenARock.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(BetweenARock);
        QuestUnlock CabinFever = new("Cabin Fever");
        CabinFever.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(CabinFever);
        QuestUnlock Contact = new("Contact!");
        Contact.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(Contact);
        QuestUnlock DarknessOfHallowvale = new("Darkness of Hallowvale");
        DarknessOfHallowvale.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(DarknessOfHallowvale);
        QuestUnlock DefenderOfVarrock = new("Defender of Varrock");
        DefenderOfVarrock.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(DefenderOfVarrock);
        QuestUnlock DeviousMinds = new("Devious Minds");
        DeviousMinds.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(DeviousMinds);
        QuestUnlock DragonSlayerI = new("Dragon Slayer I");
        DragonSlayerI.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(DragonSlayerI);
        QuestUnlock EnakhraSLament = new("Enakhra's Lament");
        EnakhraSLament.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(EnakhraSLament);
        QuestUnlock FairytaleIiCureAQueen = new("Fairytale II - Cure a Queen");
        FairytaleIiCureAQueen.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(FairytaleIiCureAQueen);
        QuestUnlock FamilyCrest = new("Family Crest");
        FamilyCrest.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(FamilyCrest);
        QuestUnlock TheFremennikIsles = new("The Fremennik Isles");
        TheFremennikIsles.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(TheFremennikIsles);
        QuestUnlock HauntedMine = new("Haunted Mine");
        HauntedMine.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(HauntedMine);
        QuestUnlock TheHeartOfDarkness = new("The Heart of Darkness");
        TheHeartOfDarkness.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(TheHeartOfDarkness);
        QuestUnlock HeroesQuest = new("Heroes' Quest");
        HeroesQuest.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(HeroesQuest);
        QuestUnlock KingSRansom = new("King's Ransom");
        KingSRansom.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(KingSRansom);
        QuestUnlock AKingdomDivided = new("A Kingdom Divided");
        AKingdomDivided.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(AKingdomDivided);
        QuestUnlock LandOfTheGoblins = new("Land of the Goblins");
        LandOfTheGoblins.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(LandOfTheGoblins);
        QuestUnlock LunarDiplomacy = new("Lunar Diplomacy");
        LunarDiplomacy.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(LunarDiplomacy);
        QuestUnlock MeatAndGreet = new("Meat and Greet");
        MeatAndGreet.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(MeatAndGreet);
        QuestUnlock MyArmSBigAdventure = new("My Arm's Big Adventure");
        MyArmSBigAdventure.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(MyArmSBigAdventure);
        QuestUnlock OneSmallFavour = new("One Small Favour");
        OneSmallFavour.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(OneSmallFavour);
        QuestUnlock ThePathOfGlouphrie = new("The Path of Glouphrie");
        ThePathOfGlouphrie.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(ThePathOfGlouphrie);
        QuestUnlock RagAndBoneManIi = new("Rag and Bone Man II");
        RagAndBoneManIi.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(RagAndBoneManIi);
        QuestUnlock RovingElves = new("Roving Elves");
        RovingElves.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(RovingElves);
        QuestUnlock RoyalTrouble = new("Royal Trouble");
        RoyalTrouble.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(RoyalTrouble);
        QuestUnlock RumDeal = new("Rum Deal");
        RumDeal.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(RumDeal);
        QuestUnlock ShadowsOfCustodia = new("Shadows of Custodia");
        ShadowsOfCustodia.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(ShadowsOfCustodia);
        QuestUnlock ATasteOfHope = new("A Taste of Hope");
        ATasteOfHope.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(ATasteOfHope);
        QuestUnlock TheRedReef = new("The Red Reef");
        TheRedReef.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(TheRedReef);
        QuestUnlock ThroneOfMiscellania = new("Throne of Miscellania");
        ThroneOfMiscellania.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(ThroneOfMiscellania);
        QuestUnlock TroubledTortugans = new("Troubled Tortugans");
        TroubledTortugans.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(TroubledTortugans);
        QuestUnlock TheGreatBrainRobbery = new("The Great Brain Robbery");
        TheGreatBrainRobbery.questDifficulty = QuestDifficulty.Experienced;
        quests.Add(TheGreatBrainRobbery);
        DefenderOfVarrock.skillRequirements.Add((Skill.Smithing, 55));
        DeviousMinds.skillRequirements.Add((Skill.Smithing, 65));
        EnakhraSLament.skillRequirements.Add((Skill.Crafting, 50));
        FamilyCrest.skillRequirements.Add((Skill.Mining, 40));
        TheGreatBrainRobbery.skillRequirements.Add((Skill.Crafting, 16));
        TheHeartOfDarkness.skillRequirements.Add((Skill.Mining, 55));
        //KingSRansom.skillRequirements.Add((Skill.Magic, 45));
        MyArmSBigAdventure.skillRequirements.Add((Skill.Farming, 29));
        RagAndBoneManIi.skillRequirements.Add((Skill.Slayer, 40));
        RoyalTrouble.skillRequirements.Add((Skill.Agility, 40));
        TheRedReef.skillRequirements.Add((Skill.Sailing, 52));
        TroubledTortugans.skillRequirements.Add((Skill.Slayer, 51));
        TheGreatBrainRobbery.questRequirements.Add(CabinFever);

        // Master quests
        QuestUnlock BeneathCursedSands = new("Beneath Cursed Sands");
        BeneathCursedSands.questDifficulty = QuestDifficulty.Master;
        quests.Add(BeneathCursedSands);
        QuestUnlock DesertTreasureI = new("Desert Treasure I");
        DesertTreasureI.questDifficulty = QuestDifficulty.Master;
        quests.Add(DesertTreasureI);
        QuestUnlock DesertTreasureIiTheFallenEmpire = new("Desert Treasure II - The Fallen Empire");
        DesertTreasureIiTheFallenEmpire.questDifficulty = QuestDifficulty.Grandmaster;
        quests.Add(DesertTreasureIiTheFallenEmpire);
        QuestUnlock DragonSlayerIi = new("Dragon Slayer II");
        DragonSlayerIi.questDifficulty = QuestDifficulty.Grandmaster;
        quests.Add(DragonSlayerIi);
        QuestUnlock DreamMentor = new("Dream Mentor");
        DreamMentor.questDifficulty = QuestDifficulty.Master;
        quests.Add(DreamMentor);
        QuestUnlock TheFremennikExiles = new("The Fremennik Exiles");
        TheFremennikExiles.questDifficulty = QuestDifficulty.Master;
        quests.Add(TheFremennikExiles);
        QuestUnlock GrimTales = new("Grim Tales");
        GrimTales.questDifficulty = QuestDifficulty.Master;
        quests.Add(GrimTales);
        QuestUnlock LegendsQuest = new("Legends' Quest");
        LegendsQuest.questDifficulty = QuestDifficulty.Master;
        quests.Add(LegendsQuest);
        QuestUnlock MakingFriendsWithMyArm = new("Making Friends with My Arm");
        MakingFriendsWithMyArm.questDifficulty = QuestDifficulty.Master;
        quests.Add(MakingFriendsWithMyArm);
        QuestUnlock MonkeyMadnessI = new("Monkey Madness I");
        MonkeyMadnessI.questDifficulty = QuestDifficulty.Master;
        quests.Add(MonkeyMadnessI);
        QuestUnlock MonkeyMadnessIi = new("Monkey Madness II");
        MonkeyMadnessIi.questDifficulty = QuestDifficulty.Grandmaster;
        quests.Add(MonkeyMadnessIi);
        QuestUnlock MourningSEndPartI = new("Mourning's End Part I");
        MourningSEndPartI.questDifficulty = QuestDifficulty.Master;
        quests.Add(MourningSEndPartI);
        QuestUnlock MourningSEndPartIi = new("Mourning's End Part II");
        MourningSEndPartIi.questDifficulty = QuestDifficulty.Master;
        quests.Add(MourningSEndPartIi);
        QuestUnlock ANightAtTheTheatre = new("A Night at the Theatre");
        ANightAtTheTheatre.questDifficulty = QuestDifficulty.Master;
        quests.Add(ANightAtTheTheatre);
        QuestUnlock PerilousMoons = new("Perilous Moons");
        PerilousMoons.questDifficulty = QuestDifficulty.Master;
        quests.Add(PerilousMoons);
        QuestUnlock SecretsOfTheNorth = new("Secrets of the North");
        SecretsOfTheNorth.questDifficulty = QuestDifficulty.Master;
        quests.Add(SecretsOfTheNorth);
        QuestUnlock SinsOfTheFather = new("Sins of the Father");
        SinsOfTheFather.questDifficulty = QuestDifficulty.Master;
        quests.Add(SinsOfTheFather);
        QuestUnlock SongOfTheElves = new("Song of the Elves");
        SongOfTheElves.questDifficulty = QuestDifficulty.Grandmaster;
        quests.Add(SongOfTheElves);
        QuestUnlock SwanSong = new("Swan Song");
        SwanSong.questDifficulty = QuestDifficulty.Master;
        quests.Add(SwanSong);
        QuestUnlock TheBloodMoonRises = new("The Blood Moon Rises");
        TheBloodMoonRises.questDifficulty = QuestDifficulty.Grandmaster;
        quests.Add(TheBloodMoonRises);
        QuestUnlock TheCurseOfArrav = new("The Curse of Arrav");
        TheCurseOfArrav.questDifficulty = QuestDifficulty.Master;
        quests.Add(TheCurseOfArrav);
        QuestUnlock TheFinalDawn = new("The Final Dawn");
        TheFinalDawn.questDifficulty = QuestDifficulty.Master;
        quests.Add(TheFinalDawn);
        QuestUnlock WhileGuthixSleeps = new("While Guthix Sleeps");
        WhileGuthixSleeps.questDifficulty = QuestDifficulty.Grandmaster;
        quests.Add(WhileGuthixSleeps);
        DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Firemaking, 75));
        DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Mining, 60));
        DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Construction, 60));
        //DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Attack, 1));
        DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Herblore, 62));
        //DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Hitpoints, 25));
        //DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Magic, 75));
        DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Runecraft, 60));
        DesertTreasureIiTheFallenEmpire.skillRequirements.Add((Skill.Thieving, 70));

        TheFremennikExiles.skillRequirements.Add((Skill.Crafting, 65));
        MakingFriendsWithMyArm.skillRequirements.Add((Skill.Firemaking, 66));
        //MourningSEndPartI.skillRequirements.Add((Skill.Ranged, 60));
        PerilousMoons.skillRequirements.Add((Skill.Slayer, 48));
        SecretsOfTheNorth.skillRequirements.Add((Skill.Agility, 69));
        TheCurseOfArrav.skillRequirements.Add((Skill.Mining, 64));
        TheFinalDawn.skillRequirements.Add((Skill.Thieving, 66));

        DragonSlayerIi.skillRequirements.Add((Skill.Agility, 60));
        DragonSlayerIi.skillRequirements.Add((Skill.Thieving, 60));
        DragonSlayerIi.skillRequirements.Add((Skill.Construction, 50));
        DragonSlayerIi.skillRequirements.Add((Skill.Smithing, 70));
        DragonSlayerIi.skillRequirements.Add((Skill.Mining, 68));
        DragonSlayerIi.skillRequirements.Add((Skill.Crafting, 62));
        //DragonSlayerIi.skillRequirements.Add((Skill.Hitpoints, 50));
        //DragonSlayerIi.skillRequirements.Add((Skill.Magic, 75));

        MonkeyMadnessIi.skillRequirements.Add((Skill.Agility, 55));
        MonkeyMadnessIi.skillRequirements.Add((Skill.Thieving, 55));
        MonkeyMadnessIi.skillRequirements.Add((Skill.Slayer, 69));
        MonkeyMadnessIi.skillRequirements.Add((Skill.Hunter, 60));
        MonkeyMadnessIi.skillRequirements.Add((Skill.Crafting, 70));
        MonkeyMadnessIi.skillRequirements.Add((Skill.Firemaking, 60));

        SongOfTheElves.skillRequirements.Add((Skill.Agility, 70));
        SongOfTheElves.skillRequirements.Add((Skill.Construction, 70));
        SongOfTheElves.skillRequirements.Add((Skill.Farming, 70));
        SongOfTheElves.skillRequirements.Add((Skill.Herblore, 70));
        SongOfTheElves.skillRequirements.Add((Skill.Hunter, 70));
        SongOfTheElves.skillRequirements.Add((Skill.Mining, 70));
        SongOfTheElves.skillRequirements.Add((Skill.Smithing, 70));
        SongOfTheElves.skillRequirements.Add((Skill.Woodcutting, 70));
        //SongOfTheElves.skillRequirements.Add((Skill.Hitpoints, 5));
        //SongOfTheElves.skillRequirements.Add((Skill.Magic, 80));
        SongOfTheElves.skillRequirements.Add((Skill.Prayer, 40));

        WhileGuthixSleeps.skillRequirements.Add((Skill.Agility, 66));
        //WhileGuthixSleeps.skillRequirements.Add((Skill.Attack, 99));
        WhileGuthixSleeps.skillRequirements.Add((Skill.Farming, 65));
        WhileGuthixSleeps.skillRequirements.Add((Skill.Herblore, 65));
        WhileGuthixSleeps.skillRequirements.Add((Skill.Hunter, 62));
        //WhileGuthixSleeps.skillRequirements.Add((Skill.Magic, 67));
        //WhileGuthixSleeps.skillRequirements.Add((Skill.Strength, 99));
        WhileGuthixSleeps.skillRequirements.Add((Skill.Thieving, 72));

        DesertTreasureIiTheFallenEmpire.questRequirements.Add(DragonSlayerIi);
        DesertTreasureIiTheFallenEmpire.questRequirements.Add(MonkeyMadnessIi);
        DragonSlayerIi.questRequirements.Add(WhileGuthixSleeps);
        DragonSlayerIi.questRequirements.Add(SongOfTheElves);
        SongOfTheElves.questRequirements.Add(DragonSlayerIi);
        TheBloodMoonRises.questRequirements.Add(SongOfTheElves);
        WhileGuthixSleeps.questRequirements.Add(DragonSlayerIi);

        // Special quests
        QuestUnlock RecipeForDisaster = new("Recipe for Disaster");
        RecipeForDisaster.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisaster);
        QuestUnlock RecipeForDisasterAnotherCookSQuest = new("Recipe for Disaster/Another Cook's Quest");
        RecipeForDisasterAnotherCookSQuest.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterAnotherCookSQuest);
        QuestUnlock RecipeForDisasterDefeatingTheCulinaromancer = new("Recipe for Disaster/Defeating the Culinaromancer");
        RecipeForDisasterDefeatingTheCulinaromancer.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterDefeatingTheCulinaromancer);
        QuestUnlock RecipeForDisasterFreeingEvilDave = new("Recipe for Disaster/Freeing Evil Dave");
        RecipeForDisasterFreeingEvilDave.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingEvilDave);
        QuestUnlock RecipeForDisasterFreeingKingAwowogei = new("Recipe for Disaster/Freeing King Awowogei");
        RecipeForDisasterFreeingKingAwowogei.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingKingAwowogei);
        QuestUnlock RecipeForDisasterFreeingPiratePete = new("Recipe for Disaster/Freeing Pirate Pete");
        RecipeForDisasterFreeingPiratePete.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingPiratePete);
        QuestUnlock RecipeForDisasterFreeingSirAmikVarze = new("Recipe for Disaster/Freeing Sir Amik Varze");
        RecipeForDisasterFreeingSirAmikVarze.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingSirAmikVarze);
        QuestUnlock RecipeForDisasterFreeingSkrachUglogwee = new("Recipe for Disaster/Freeing Skrach Uglogwee");
        RecipeForDisasterFreeingSkrachUglogwee.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingSkrachUglogwee);
        QuestUnlock RecipeForDisasterFreeingTheGoblinGenerals = new("Recipe for Disaster/Freeing the Goblin generals");
        RecipeForDisasterFreeingTheGoblinGenerals.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingTheGoblinGenerals);
        QuestUnlock RecipeForDisasterFreeingTheLumbridgeGuide = new("Recipe for Disaster/Freeing the Lumbridge Guide");
        RecipeForDisasterFreeingTheLumbridgeGuide.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingTheLumbridgeGuide);
        QuestUnlock RecipeForDisasterFreeingTheMountainDwarf = new("Recipe for Disaster/Freeing the Mountain Dwarf");
        RecipeForDisasterFreeingTheMountainDwarf.questDifficulty = QuestDifficulty.Special;
        quests.Add(RecipeForDisasterFreeingTheMountainDwarf);
        RecipeForDisasterAnotherCookSQuest.skillRequirements.Add((Skill.Cooking, 10));
        RecipeForDisasterFreeingKingAwowogei.skillRequirements.Add((Skill.Cooking, 70));
        RecipeForDisasterFreeingPiratePete.skillRequirements.Add((Skill.Cooking, 31));
        RecipeForDisasterFreeingSkrachUglogwee.skillRequirements.Add((Skill.Cooking, 41));
        RecipeForDisasterFreeingTheLumbridgeGuide.skillRequirements.Add((Skill.Cooking, 40));

        return quests;
    }
}
